#!/usr/bin/env python

import requests
import json

raw_cookie = '''\
cookie	STAREIG=1190da722c3715d5c5099e24cdd5532723ab1aab
cookie	_ntes_nnid=5b0efbe73aeaf35ae6159bfeb94490f9,1521719982365
cookie	_ntes_nuid=5b0efbe73aeaf35ae6159bfeb94490f9
cookie	NTES_YD_SESS=YT3NSaeqowAfe6y0wmhb3yR5mKgE5JtrYFI5bqpYG5s0Xu9MX1ahwnx0PBQHRbbZ7Kcd978Lnun3KNQ9x6TttmDdc0tkEejMme87iJ5RRAAonQjcS4HUs4U.G1TFl9mu8MNADvEEPba8x7QGNelNDHkc2sfUJbFEM8C93kPKJcUz54EiFptKiVbOn3BP7HozEkmbjiCZT4dDZsgKC8sJsb6hfkKLJU.F9OCbR22QdkSTy
cookie	_ga=GA1.2.2128816940.1518185268
cookie	mp_MA-9E66-C87EFACB60BC_hubble=%7B%22sessionReferrer%22%3A%20%22%22%2C%22updatedTime%22%3A%201522713739556%2C%22sessionStartTime%22%3A%201522713739123%2C%22deviceUdid%22%3A%20%227aadfc5d-999c-4fef-9a04-f9ab65b23cc4%22%2C%22initial_referrer%22%3A%20%22%24direct%22%2C%22initial_referring_domain%22%3A%20%22%24direct%22%2C%22persistedTime%22%3A%201521589855690%2C%22LASTEVENT%22%3A%20%7B%22eventId%22%3A%20%22da_u_login%22%2C%22time%22%3A%201522713739556%7D%2C%22sessionUuid%22%3A%20%2201ac3545-c4b1-4412-8731-cdc77c12cea9%22%2C%22user_id%22%3A%20189678%7D
cookie	NTES_YD_SESS=YT3NSaeqowAfe6y0wmhb3yR5mKgE5JtrYFI5bqpYG5s0Xu9MX1ahwnx0PBQHRbbZ7Kcd978Lnun3KNQ9x6TttmDdc0tkEejMme87iJ5RRAAonQjcS4HUs4U.G1TFl9mu8MNADvEEPba8x7QGNelNDHkc2sfUJbFEM8C93kPKJcUz54EiFptKiVbOn3BP7HozEkmbjiCZT4dDZsgKC8sJsb6hfkKLJU.F9OCbR22QdkSTy
'''.strip()

cookies = {}

for cookie in raw_cookie.splitlines():
	cookie_key, cookie_value = cookie.split()[-1].strip().split('=')
	cookies[cookie_key.strip()] = cookie_value.strip()

headers = {
    'Host': 'star.8.163.com',
    'Origin': 'https://star.8.163.com',
    'Accept': 'application/json, text/plain, */*',
    'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_1_2 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Mobile/15B202star_client_1.0.0',
    'Referer': 'https://star.8.163.com/m',
    'Accept-Language': 'zh-cn',
    'X-Requested-With': 'XMLHttpRequest',
}

# 请求领取coin接口
def collectCoins(coinId):
	headers = {
	    'Host': 'star.8.163.com',
	    'Accept': 'application/json, text/plain, */*',
	    'X-Requested-With': 'XMLHttpRequest',
	    'Accept-Language': 'zh-cn',
	    'Cache-Control': 'max-age=0',
	    'Content-Type': 'application/json;charset=UTF-8',
	    'Origin': 'https://star.8.163.com',
	    'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_1_2 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Mobile/15B202star_client_1.0.0',
	    'Referer': 'https://star.8.163.com/m',
	}

	data = '{"id":%s}' % coinId
	response = requests.post('https://star.8.163.com/api/starUserCoin/collectUserCoin', headers=headers, cookies=cookies, data=data)
	print(response.text)
	print(data)


# 1、请求首页数据，检查是否有coin可以收集。有则将coin保存到列表容器
response = requests.post('https://star.8.163.com/api/home/index', headers=headers, cookies=cookies)
jsonData = json.loads(response.text)

print(jsonData)

collectCoinsList = jsonData['data']['collectCoins']
print(collectCoinsList)
if len(collectCoinsList) == 0:
	print('当前没有黑钻可以领取...')
else:
	# 2、检查coin列表容器是否有值，遍历请求领取coin接口
	for collectCoinsItem in collectCoinsList:
		print(collectCoinsItem)
		collectCoins(collectCoinsItem['id'])
